### ISSUE TITLE
LoneJS Parts (to-dos)

### ISSUE THREAD

**Issue by robbobfrh84** [robbobfrh84/loneJS-Toolkit#16]
*page-handling
- naming conventions (decide on PAGE-whatever, or PAGE-WHATEVER)

*dynamic-html
- Jump into 3-deep concept for html. Create side-by-side dynamic + hardcoded
- Fix confusing ... <input often will use both val="" and value="" (value is html reserved, and we already use name..... dataVal? check where this is an issues, prob chronenberg or life-track). ALSO: there are some html attributes that you've used, like for, maybe sweep all attributes and rename as forJS, varJS, ifJS...? serveJS, servedJS... etc...
- I removed all passed updates... like: `...}, true)` just hard code c.flushData(). Just a reminder to note this if confusing. 

*request-handing
- Add _REQ class to data.js or (have apps.js be in basic code base? with c.I('') stuff?)

*components
- Reduce re-rendering of components (especially embedded)

*data-handling
*getting-started
*javascript-in-components

--
- [ ] #14 - the update issue...
- [ ] #15 - Get elements by "CLASS" name
- [ ] #11 - Waiting for API allows style to show a nasty bundle of var names...
- [ ] #7 - bracket notation with `-` > ["-lat"] causes error.

----
