### ISSUE TITLE
Updating loneJS repo checklist/step-by-step

### ISSUE THREAD

**Issue by robbobfrh84** [robbobfrh84/loneJS-Toolkit#3]
- [ ] make sure and address version notes. this change may be to much, but do a light summery just to get the flow started.
- [ ] remove docs from loneJS repo and point link to loneJS.tech/#docs in readme.md instead.
- [ ] make sure to parse out all tester code (NOT JUST loneJS-lib)! like changes in index.html could be relivant! (sources and when they're added to the script could mess stuff up!)
- [ ] ALSO polyfill.js will need to be altered to remove '../' that has it bounce up a dir. 
- [ ] Let consider merging all loneJS files into one file. Well noted separation, 4 files is just confusing, if most poeple will never go into them. those who will will be able to figure there way through. OR: test again by loading them from one .js file, I might have not properly loaded it into the HEAD when i did that last time. 
- [ ] Copy all files from loneJS repo and paste them into toolkits archive with current Version#
- [ ] When tested and done,  relevant project files /new version will just be dragged/dropped into loneJS.
- [ ] Transfer appropriate outdated toolkit files into archive with the updated version in archive as well. 
- [ ] Don't forget to merge with master brach!
- [ ] Make an "update to new version" and "adding issues to current version" flow chart. Maybe put it in your _lonejs_central.md...?
